model_name: "./Qwen2.5-1.5B"  
train_path: "./data/train.json"
val_path: "./data/val.json"
train_val_path: "./data/train_val.json"
save_path: "./save_model"

# 训练参数
seed: 42
epochs: 5
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
warmup_steps: 50
weight_decay: 0.01
logging_steps: 1
